apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-author
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app-author
  template:
    metadata:
      labels:
        app: app-author
    spec:
      containers:
        - name: app-author
          image: just5ebas/ejemplo05_author
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              port: 8080
              path: /q/health/live
            initialDelaySeconds: 20
            periodSeconds: 5
          env:
            - name: QUARKUS_DATASOURCE_USERNAME
              value: distibuida_user
            - name: QUARKUS_DATASOURCE_PASSWORD
              value: jJ4oJSuEbOWXJVyGVSdfmG5v0Pzn3YPX
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: jdbc:postgresql://dpg-cqc4g3d6l47c73ctsa3g-a.oregon-postgres.render.com/distibuida
            - name: QUARKUS_HTTP_PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: app-author-service
spec:
  type: ClusterIP
  selector:
    app: app-author
  ports:
   - protocol: TCP
     port: 8080
     targetPort: 8080